# Generated by Django 2.2.14 on 2020-08-02 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoPorudcto',
            new_name='TipoProducto',
        ),
    ]
